version: "3"

services:
  db:
    restart: always
    container_name: "dice_and_die_db"
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dice_and_die
    volumes:
      - mysql-data:/var/lib/mysql
      - ./app/db/:/docker-entrypoint-initdb.d  # Run all the scrips in the sql_scripts
    networks:
      - mysql  # Unir este servicio a la red 'mysql'

  api:
    restart: always
    container_name: "dice_and_die_api"
    image: "dice_and_die_api"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/dice_and_die_api
    depends_on:
      - db
    networks:
      - mysql  # Unir este servicio a la red 'mysql'

networks:
  mysql:
    external: False

volumes:
  mysql-data:  # Definición del volumen para MySQL