name: CI
on: workflow_dispatch
jobs: 
  dice-and-die-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello tobe"
      - name: Print Goodbye
        run: echo "Done - bye!"
  

